Repository SemtleApp/SERVER, pull requests merged in 2023-08, with the labels that each got.

#31 [Feat/#29] 스터디룸 게시글 상세조회
  src/main/java/com/semtleapp/semtleapp/semtlestudy/controller/SemtleStudyController.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/convertor/SemtleStudyConvertor.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/dto/GetStudyPostDetailResDto.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/repository/SemtleStudyPostRepository.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/service/SemtleStudyService.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/service/SemtleStudyServiceImpl.java
Labels: 윤규

#38 [Feat/#37] 스터디 게시글 수정
  src/main/java/com/semtleapp/semtleapp/global/entity/BaseTimeEntity.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/controller/SemtleStudyController.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/convertor/SemtleStudyConvertor.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/dto/ModifyStudyPostReqDto.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/dto/ModifyStudyPostResDto.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/entity/SemtleStudyPost.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/service/SemtleStudyService.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/service/SemtleStudyServiceImpl.java
Labels: 윤규

#40 [Fix/#39] semtlepost package 삭제
  src/main/java/com/semtleapp/semtleapp/file/controller/FileController.java
  src/main/java/com/semtleapp/semtleapp/semtlebook/controller/SemtleBookController.java
  src/main/java/com/semtleapp/semtleapp/semtlepost/controller/SemtlePostController.java
  src/main/java/com/semtleapp/semtleapp/semtlepost/dto/SemtlePostDto.java
  src/main/java/com/semtleapp/semtleapp/semtlepost/entity/SemtlePost.java
  src/main/java/com/semtleapp/semtleapp/semtlepost/repository/SemtlePostRepository.java
  src/main/java/com/semtleapp/semtleapp/semtlepost/service/SemtlePostService.java
  src/main/java/com/semtleapp/semtleapp/semtlepost/service/SemtlePostServiceImpl.java
  src/main/java/com/semtleapp/semtleapp/semtleuser/dto/SemtleUserDto.java
  src/main/java/com/semtleapp/semtleapp/semtleuser/entity/SemtleUser.java
Labels: 윤규

#42 [Feat/#41] 스터디 게시글 삭제
  src/main/java/com/semtleapp/semtleapp/global/exception/ErrorCode.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/controller/SemtleStudyController.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/dto/DeleteStudyPostResDto.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/service/SemtleStudyService.java
  src/main/java/com/semtleapp/semtleapp/semtlestudy/service/SemtleStudyServiceImpl.java
Labels: 윤규

#49 [Feat/#46] 회비 미납부자 조회 기능 추가
  src/main/java/com/semtleapp/semtleapp/semtledues/controller/SemtleDuesController.java
  src/main/java/com/semtleapp/semtleapp/semtledues/convertor/SemtleDuesConvertor.java
  src/main/java/com/semtleapp/semtleapp/semtledues/dto/GetIngResDto.java
  src/main/java/com/semtleapp/semtleapp/semtledues/dto/Status.java
  src/main/java/com/semtleapp/semtleapp/semtledues/entity/SemtleDues.java
  src/main/java/com/semtleapp/semtleapp/semtledues/repository/SemtleDuesRepository.java
  src/main/java/com/semtleapp/semtleapp/semtledues/service/SemtleDuesService.java
  src/main/java/com/semtleapp/semtleapp/semtledues/service/SemtleDuesServiceImpl.java
Labels: 동헌

#52 [Feat/#36] 공지사항 게시글 전체조회 및 상세조회
  src/main/java/com/semtleapp/semtleapp/semtlenotice/controller/SemtleNoticeController.java
  src/main/java/com/semtleapp/semtleapp/semtlenotice/dto/SemtleNoticeRes.java
  src/main/java/com/semtleapp/semtleapp/semtlenotice/service/SemtleNoticeService.java
  src/main/java/com/semtleapp/semtleapp/semtlenotice/service/SemtleNoticeServiceImpl.java
Labels: 다빈

#58 [Feat/#57] : 회비 납부 상태 수정기능 추가
  src/main/java/com/semtleapp/semtleapp/semtledues/controller/SemtleDuesController.java
  src/main/java/com/semtleapp/semtleapp/semtledues/dto/ModifyDuesReqDto.java
  src/main/java/com/semtleapp/semtleapp/semtledues/dto/ModifyDuesResDto.java
  src/main/java/com/semtleapp/semtleapp/semtledues/repository/SemtleDuesRepository.java
  src/main/java/com/semtleapp/semtleapp/semtledues/service/SemtleDuesService.java
  src/main/java/com/semtleapp/semtleapp/semtledues/service/SemtleDuesServiceImpl.java
  src/main/java/com/semtleapp/semtleapp/semtleuser/entity/SemtleUserInfo.java
Labels: 동헌
